### PR TITLE
Streams2 working

### PR DESCRIPTION
**Pull request by skylize**

### CODE REVIEW

**Comment by skylize** [comment]
The commit w/ message ["fixed missing error function"](https://github.com/skylize/node-optipng/commit/30746d33b56d96d98eddfc82a7e6a483efa99432) and hash c28a5df. has minimal changes to implement Streams2 and should look very familiar to your own code. I did refactoring and renaming in the [following commit](https://github.com/skylize/node-optipng/commit/db43fd4803e8c61ae1a335b7e4377e655369126c), not realizing I can't make a separate pull request.

**Comment by papandreou** [comment]
Great, thanks for the contribution!

**Comment by papandreou** [comment]
Oh wait, I forgot I don't have travis up and running for this repo. After merging, all 4 tests fail with:

```
     Uncaught TypeError: Object #<OptiPng> has no method 'isPaused'
      at OptiPng._read (lib/OptiPng.js:36:11)
```

Care to take a look at that?

**Comment by skylize** [comment]
Hmm. It looks like I never commited some tweaks I made to the tests. But, you shouldn't have gotten that error. I did see that error once a ways back, but can't remember it's cause.

I just pushed my latest, including the updated tests. I'm showing pass on all 4 both Windows and Linux. Take a look at the changes to tests and make sure you're comfy with them. 

I changed the test to: 
`1.`Allow the binary pathname to optionally include '.exe' for Windows.
`2.`Allow an error to also send a `null` chunk and emit 'end' event.  *(Emitting an error does not necessarily end the stream, so ondata listeners might continue listening forever even though the stream is effectively dead.)*
`3.`Fail test 1 if an error is emitted.

**Comment by papandreou** [comment]
After merging the current state of skylize/master the tests still fail:

```
  1) OptiPng should produce a smaller file when run with -o7 on a suboptimal PNG:
     Uncaught TypeError: Object #<OptiPng> has no method 'isPaused'
      at OptiPng._read (lib/OptiPng.js:36:11)
      at OptiPng.Readable.read (_stream_readable.js:323:10)
      at OptiPng.<anonymous> (_stream_readable.js:747:45)
      at _stream_readable.js:776:12

  2) OptiPng should not emit data events while paused:
     Uncaught TypeError: Object #<OptiPng> has no method 'isPaused'
      at OptiPng.onBinComplete (lib/OptiPng.js:87:18)
      at Process.ChildProcess._handle.onexit (child_process.js:809:12)

  3) OptiPng should emit an error if an invalid image is processed:
     Uncaught TypeError: Object #<OptiPng> has no method 'isPaused'
      at OptiPng._read (lib/OptiPng.js:36:11)
      at OptiPng.Readable.read (_stream_readable.js:323:10)
      at OptiPng.<anonymous> (_stream_readable.js:747:45)
      at _stream_readable.js:776:12

  4) OptiPng should emit a single error if an invalid command line is specified:
     Uncaught TypeError: Object #<OptiPng> has no method 'isPaused'
      at OptiPng._read (lib/OptiPng.js:36:11)
      at OptiPng.Readable.read (_stream_readable.js:323:10)
      at OptiPng.<anonymous> (_stream_readable.js:747:45)
      at _stream_readable.js:776:12
```

**Comment by skylize** [comment]
I see. Fails in node 0.10. I was using 0.12.4. I'll see what I can do about that.

**Comment by papandreou** [comment]
Oh, that explains it.

I rolled back the merge (force pushed) and added Travis integration so that PRs will be built on both node.js 0.10 and 0.12. Seems like this PR cannot be reopened, but please open a new one once it builds on 0.10 for you locally.

**Pull request merged**
